app-pm2:
  container_name: app-pm2
  #构建容器器
  build: .
  # volumes:
  # - .:/usr/src/app
  ports:
    - "3000:3000"
  # version: '3.1'
  # services:
  #   mongo:
  #     image: mongo
  #     restart: always
  #     ports:
  #       - 27017:27017
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081  